function playRandomSound() {
    var soundList = [
        { src: 'mp3/ChinaBT-04.mp3', image: 'img/image04.jpg' },
        { src: 'mp3/ChinaBT-05.mp3', image: 'img/image04.jpg' },
        { src: 'mp3/ChinaBT-06.mp3', image: 'img/image06.jpg' },
        { src: 'mp3/ChinaBT-07.mp3', image: 'img/image06.jpg' },
        { src: 'mp3/ChinaBT-08.mp3', image: 'img/image08.jpg' },
        { src: 'mp3/ChinaBT-09.mp3', image: 'img/image08.jpg' },
        { src: 'mp3/ChinaBT-10.mp3', image: 'img/image10.jpg' },
        { src: 'mp3/ChinaBT-11.mp3', image: 'img/image10.jpg' },
        { src: 'mp3/ChinaBT-12.mp3', image: 'img/image12.jpg' },
        { src: 'mp3/ChinaBT-13.mp3', image: 'img/image12.jpg' },
        { src: 'mp3/ChinaBT-14.mp3', image: 'img/image14.jpg' },
        { src: 'mp3/ChinaBT-15.mp3', image: 'img/image14.jpg' },
        { src: 'mp3/ChinaBT-16.mp3', image: 'img/image16.jpg' },
        { src: 'mp3/ChinaBT-17.mp3', image: 'img/image16.jpg' },
        { src: 'mp3/ChinaBT-18.mp3', image: 'img/image18.jpg' },
        { src: 'mp3/ChinaBT-19.mp3', image: 'img/image19.jpg' },
        { src: 'mp3/ChinaBT-20.mp3', image: 'img/image20.jpg' },
        { src: 'mp3/ChinaBT-21.mp3', image: 'img/image20.jpg' },
        { src: 'mp3/ChinaBT-22.mp3', image: 'img/image22.jpg' },
        { src: 'mp3/ChinaBT-23.mp3', image: 'img/image22.jpg' },
        { src: 'mp3/ChinaBT-24.mp3', image: 'img/image24.jpg' },
        { src: 'mp3/ChinaBT-25.mp3', image: 'img/image24.jpg' },
        { src: 'mp3/ChinaBT-26.mp3', image: 'img/image26.jpg' },
        { src: 'mp3/ChinaBT-27.mp3', image: 'img/image26.jpg' },
        { src: 'mp3/ChinaBT-28.mp3', image: 'img/image28.jpg' },
        { src: 'mp3/ChinaBT-29.mp3', image: 'img/image28.jpg' },
        { src: 'mp3/ChinaBT-30.mp3', image: 'img/image30.jpg' },
        { src: 'mp3/ChinaBT-31.mp3', image: 'img/image30.jpg' },
        { src: 'mp3/ChinaBT-32.mp3', image: 'img/image32.jpg' },
        { src: 'mp3/ChinaBT-33.mp3', image: 'img/image32.jpg' },
        { src: 'mp3/ChinaBT-34.mp3', image: 'img/image34.jpg' },
        { src: 'mp3/ChinaBT-35.mp3', image: 'img/image34.jpg' },
        { src: 'mp3/ChinaBT-36.mp3', image: 'img/image36.jpg' },
        { src: 'mp3/ChinaBT-37.mp3', image: 'img/image36.jpg' },
        { src: 'mp3/ChinaBT-38.mp3', image: 'img/image38.jpg' },
        { src: 'mp3/ChinaBT-39.mp3', image: 'img/image38.jpg' },
        { src: 'mp3/ChinaBT-40.mp3', image: 'img/image40.jpg' },
        { src: 'mp3/ChinaBT-41.mp3', image: 'img/image40.jpg' },
        { src: 'mp3/ChinaBT-42.mp3', image: 'img/image42.jpg' },
        { src: 'mp3/ChinaBT-43.mp3', image: 'img/image42.jpg' },
        { src: 'mp3/ChinaBT-44.mp3', image: 'img/image44.jpg' },
        { src: 'mp3/ChinaBT-45.mp3', image: 'img/image44.jpg' },
        { src: 'mp3/ChinaBT-46.mp3', image: 'img/image46.jpg' },
        { src: 'mp3/ChinaBT-47.mp3', image: 'img/image46.jpg' },
        { src: 'mp3/ChinaBT-48.mp3', image: 'img/image48.jpg' },
        { src: 'mp3/ChinaBT-49.mp3', image: 'img/image48.jpg' },
        { src: 'mp3/ChinaBT-50.mp3', image: 'img/image50.jpg' },
        { src: 'mp3/ChinaBT-51.mp3', image: 'img/image50.jpg' },
        { src: 'mp3/ChinaBT-52.mp3', image: 'img/image52.jpg' },
        { src: 'mp3/ChinaBT-53.mp3', image: 'img/image52.jpg' },
        { src: 'mp3/ChinaBT-54.mp3', image: 'img/image54.jpg' },
        { src: 'mp3/ChinaBT-55.mp3', image: 'img/image54.jpg' },
        { src: 'mp3/ChinaBT-56.mp3', image: 'img/image56.jpg' },
        { src: 'mp3/ChinaBT-57.mp3', image: 'img/image56.jpg' },
        { src: 'mp3/ChinaBT-58.mp3', image: 'img/image58.jpg' },
        { src: 'mp3/ChinaBT-59.mp3', image: 'img/image58.jpg' },
        { src: 'mp3/ChinaBT-60.mp3', image: 'img/image60.jpg' },
        { src: 'mp3/ChinaBT-61.mp3', image: 'img/image60.jpg' },
        { src: 'mp3/ChinaBT-62.mp3', image: 'img/image62.jpg' },
        { src: 'mp3/ChinaBT-63.mp3', image: 'img/image62.jpg' },
        { src: 'mp3/ChinaBT-64.mp3', image: 'img/image64.jpg' },
        { src: 'mp3/ChinaBT-65.mp3', image: 'img/image64.jpg' },
        { src: 'mp3/ChinaBT-66.mp3', image: 'img/image66.jpg' },
        { src: 'mp3/ChinaBT-67.mp3', image: 'img/image66.jpg' },
        { src: 'mp3/ChinaBT-68.mp3', image: 'img/image68.jpg' },
        { src: 'mp3/ChinaBT-69.mp3', image: 'img/image68.jpg' },
        { src: 'mp3/ChinaBT-70.mp3', image: 'img/image70.jpg' },
        { src: 'mp3/ChinaBT-71.mp3', image: 'img/image70.jpg' },
        { src: 'mp3/ChinaBT-72.mp3', image: 'img/image72.jpg' },
        { src: 'mp3/ChinaBT-73.mp3', image: 'img/image72.jpg' },
        { src: 'mp3/ChinaBT-74.mp3', image: 'img/image74.jpg' },
        { src: 'mp3/ChinaBT-75.mp3', image: 'img/image74.jpg' },
        { src: 'mp3/ChinaBT-76.mp3', image: 'img/image76.jpg' },
        { src: 'mp3/ChinaBT-77.mp3', image: 'img/image76.jpg' },
        { src: 'mp3/ChinaBT-78.mp3', image: 'img/image78.jpg' },
        { src: 'mp3/ChinaBT-79.mp3', image: 'img/image78.jpg' },
        { src: 'mp3/ChinaBT-80.mp3', image: 'img/image80.jpg' },
        { src: 'mp3/ChinaBT-81.mp3', image: 'img/image80.jpg' },
        { src: 'mp3/ChinaBT-82.mp3', image: 'img/image82.jpg' },
        { src: 'mp3/ChinaBT-83.mp3', image: 'img/image82.jpg' },
        { src: 'mp3/ChinaBT-84.mp3', image: 'img/image84.jpg' },
        { src: 'mp3/ChinaBT-85.mp3', image: 'img/image84.jpg' },
        { src: 'mp3/ChinaBT-86.mp3', image: 'img/image86.jpg' },
        { src: 'mp3/ChinaBT-87.mp3', image: 'img/image86.jpg' },
        { src: 'mp3/ChinaBT-88.mp3', image: 'img/image88.jpg' },
        { src: 'mp3/ChinaBT-89.mp3', image: 'img/image88.jpg' },
        { src: 'mp3/ChinaBT-90.mp3', image: 'img/image90.jpg' },
        { src: 'mp3/ChinaBT-91.mp3', image: 'img/image90.jpg' },
        { src: 'mp3/ChinaBT-92.mp3', image: 'img/image92.jpg' },
        { src: 'mp3/ChinaBT-93.mp3', image: 'img/image92.jpg' },
        { src: 'mp3/ChinaBT-94.mp3', image: 'img/image94.jpg' },
        { src: 'mp3/ChinaBT-95.mp3', image: 'img/image94.jpg' },
        { src: 'mp3/ChinaBT-96.mp3', image: 'img/image96.jpg' },
        { src: 'mp3/ChinaBT-97.mp3', image: 'img/image96.jpg' },
        { src: 'mp3/ChinaBT-98.mp3', image: 'img/image98.jpg' },
        { src: 'mp3/ChinaBT-99.mp3', image: 'img/image98.jpg' },
        { src: 'mp3/ChinaBT-100.mp3', image: 'img/image100.jpg' },
        { src: 'mp3/ChinaBT-101.mp3', image: 'img/image100.jpg' },
        { src: 'mp3/ChinaBT-102.mp3', image: 'img/image102.jpg' },
        { src: 'mp3/ChinaBT-103.mp3', image: 'img/image102.jpg' },
        { src: 'mp3/ChinaBT-104.mp3', image: 'img/image104.jpg' },
        { src: 'mp3/ChinaBT-105.mp3', image: 'img/image104.jpg' },
        { src: 'mp3/ChinaBT-106.mp3', image: 'img/image106.jpg' },
        { src: 'mp3/ChinaBT-107.mp3', image: 'img/image106.jpg' },
        { src: 'mp3/ChinaBT-108.mp3', image: 'img/image108.jpg' },
        { src: 'mp3/ChinaBT-109.mp3', image: 'img/image108.jpg' }
      
      // 必要なだけ追加できます
    ];
  
    var randomIndex = Math.floor(Math.random() * soundList.length);
    var randomSound = soundList[randomIndex];
  
    var audio = new Audio(randomSound.src);
  
    audio.addEventListener('ended', function() {
      document.getElementById('image').src = randomSound.image;
    });
  
    audio.play();
  }
  